import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFSection {
  title: string;
  content: HTMLElement | string;
  type: 'chart' | 'table' | 'text' | 'image';
  pageBreakBefore?: boolean;
}

export interface PDFExportOptions {
  title: string;
  subtitle?: string;
  includeBranding: boolean;
  pageSize: 'a4' | 'letter';
  orientation: 'portrait' | 'landscape';
  includeTableOfContents: boolean;
  sections: PDFSection[];
  footer?: string;
  generatedBy: string;
  generatedAt: string;
  schoolName?: string;
  schoolLogo?: string;
}

/**
 * Export content to PDF with school branding and formatting
 */
export const exportToPDF = async (options: PDFExportOptions): Promise<void> => {
  const {
    title,
    subtitle,
    includeBranding,
    pageSize,
    orientation,
    includeTableOfContents,
    sections,
    footer,
    generatedBy,
    generatedAt,
    schoolName,
    schoolLogo,
  } = options;

  // Create PDF document
  const pdf = new jsPDF({
    orientation,
    unit: 'mm',
    format: pageSize,
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  let yPosition = margin;

  // Helper function to add header
  const addHeader = () => {
    yPosition = margin;

    if (includeBranding && schoolLogo) {
      // Add school logo (if available)
      try {
        pdf.addImage(schoolLogo, 'PNG', margin, yPosition, 30, 30);
        yPosition += 35;
      } catch (error) {
        console.error('Error adding logo:', error);
      }
    }

    if (includeBranding && schoolName) {
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text(schoolName, margin, yPosition);
      yPosition += 10;
    }

    // Add title
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title, margin, yPosition);
    yPosition += 8;

    if (subtitle) {
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(subtitle, margin, yPosition);
      yPosition += 8;
    }

    // Add horizontal line
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 5;
  };

  // Helper function to add footer
  const addFooter = (pageNum: number) => {
    const footerY = pageHeight - margin;
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    
    if (footer) {
      pdf.text(footer, margin, footerY);
    }
    
    // Add page number
    pdf.text(
      `Page ${pageNum}`,
      pageWidth - margin - 15,
      footerY
    );

    // Add generation info
    pdf.text(
      `Generated by ${generatedBy} on ${generatedAt}`,
      margin,
      footerY + 5
    );
  };

  // Add first page header
  addHeader();

  // Table of contents
  if (includeTableOfContents && sections.length > 0) {
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Table of Contents', margin, yPosition);
    yPosition += 8;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    sections.forEach((section, index) => {
      if (yPosition > pageHeight - 30) {
        pdf.addPage();
        addHeader();
      }
      pdf.text(`${index + 1}. ${section.title}`, margin + 5, yPosition);
      yPosition += 6;
    });

    pdf.addPage();
    addHeader();
  }

  // Process sections
  for (let i = 0; i < sections.length; i++) {
    const section = sections[i];

    if (section.pageBreakBefore && i > 0) {
      pdf.addPage();
      addHeader();
    }

    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      pdf.addPage();
      addHeader();
    }

    // Add section title
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(section.title, margin, yPosition);
    yPosition += 8;

    // Add section content based on type
    if (section.type === 'text' && typeof section.content === 'string') {
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      const lines = pdf.splitTextToSize(section.content, pageWidth - 2 * margin);
      
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - 30) {
          pdf.addPage();
          addHeader();
        }
        pdf.text(line, margin, yPosition);
        yPosition += 5;
      });
    } else if (section.content instanceof HTMLElement) {
      try {
        // Render HTML element to canvas
        const canvas = await html2canvas(section.content, {
          scale: 2,
          useCORS: true,
          logging: false,
        });

        const imgData = canvas.toDataURL('image/png');
        const imgWidth = pageWidth - 2 * margin;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        // Check if image fits on current page
        if (yPosition + imgHeight > pageHeight - 30) {
          pdf.addPage();
          addHeader();
        }

        pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
        yPosition += imgHeight + 5;
      } catch (error) {
        console.error('Error rendering content to PDF:', error);
        pdf.setFontSize(10);
        pdf.text('Error rendering content', margin, yPosition);
        yPosition += 10;
      }
    }

    yPosition += 5;
  }

  // Add footer to all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter(i);
  }

  // Save the PDF
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `${title.replace(/\s+/g, '_')}_${timestamp}.pdf`;
  pdf.save(filename);
};

/**
 * Export a simple report with basic formatting
 */
export const exportSimpleReport = async (
  title: string,
  content: HTMLElement,
  options?: Partial<PDFExportOptions>
): Promise<void> => {
  const defaultOptions: PDFExportOptions = {
    title,
    includeBranding: true,
    pageSize: 'a4',
    orientation: 'portrait',
    includeTableOfContents: false,
    sections: [
      {
        title: 'Report',
        content,
        type: 'chart',
      },
    ],
    generatedBy: 'System',
    generatedAt: new Date().toLocaleDateString(),
    ...options,
  };

  await exportToPDF(defaultOptions);
};

/**
 * Create a downloadable PDF blob
 * Returns a blob that can be uploaded or further processed
 */
export const createPDFBlob = async (options: PDFExportOptions): Promise<Blob> => {
  const pdf = new jsPDF({
    orientation: options.orientation,
    unit: 'mm',
    format: options.pageSize,
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let yPosition = margin;

  // Add title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(options.title, margin, yPosition);
  yPosition += 10;

  if (options.subtitle) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(options.subtitle, margin, yPosition);
    yPosition += 10;
  }

  // Process sections
  for (const section of options.sections) {
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = margin;
    }

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(section.title, margin, yPosition);
    yPosition += 8;

    if (section.type === 'text' && typeof section.content === 'string') {
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      const lines = pdf.splitTextToSize(section.content, pageWidth - 2 * margin);
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          pdf.addPage();
          yPosition = margin;
        }
        pdf.text(line, margin, yPosition);
        yPosition += 5;
      });
    }

    yPosition += 5;
  }
  
  return pdf.output('blob');
};
