/**
 * Pension Calculator Utility
 * Handles all pension-related calculations for staff PAYE
 */

import type { 
    StaffPension, 
    PensionContribution, 
    PensionCalculationResult,
    PensionSummary,
    ContributionInputType 
} from '../types';

/**
 * Calculate contribution amount based on type (percentage or fixed)
 */
function calculateContributionAmount(
    grossSalary: number,
    type: ContributionInputType,
    value: number
): number {
    if (type === 'percentage') {
        return (grossSalary * value) / 100;
    } else {
        // For fixed amount, cap at gross salary to avoid negative net pay
        return Math.min(value, grossSalary);
    }
}

/**
 * Calculate monthly pension contributions
 * @param grossSalary - Staff member's gross salary for the month
 * @param config - Staff pension configuration
 * @returns Calculated pension amounts
 */
export function calculateMonthlyPension(
    grossSalary: number,
    config: StaffPension
): PensionCalculationResult {
    // Employee contribution (always active when enrolled)
    const employeeContribution = config.is_enrolled
        ? calculateContributionAmount(
            grossSalary,
            config.employee_contribution_type,
            config.employee_contribution_value
        )
        : 0;

    // Employer contribution (toggle on/off)
    const employerContribution = config.is_enrolled && config.employer_contribution_enabled
        ? calculateContributionAmount(
            grossSalary,
            config.employer_contribution_type,
            config.employer_contribution_value
        )
        : 0;

    // Voluntary contribution (toggle on/off)
    const voluntaryContribution = config.is_enrolled && config.voluntary_contribution_enabled
        ? calculateContributionAmount(
            grossSalary,
            config.voluntary_contribution_type,
            config.voluntary_contribution_value
        )
        : 0;

    const totalContribution = employeeContribution + employerContribution + voluntaryContribution;
    const deductionFromSalary = employeeContribution + voluntaryContribution;

    return {
        employeeContribution,
        employerContribution,
        voluntaryContribution,
        totalContribution,
        deductionFromSalary,
    };
}

/**
 * Build a pension contribution record for storage
 * @param config - Staff pension configuration
 * @param grossSalary - Staff member's gross salary
 * @param month - Contribution month (first day of month)
 * @param previousContributions - Previous contribution records for cumulative calculations
 * @param payrollRunId - Optional payroll run ID
 * @returns Complete pension contribution record ready for database insertion
 *          Note: 'id' and 'created_at' are omitted as they are auto-generated by the database
 */
export function buildContributionRecord(
    config: StaffPension,
    grossSalary: number,
    month: Date,
    previousContributions: PensionContribution[],
    payrollRunId?: number
): Omit<PensionContribution, 'id' | 'created_at'> {
    // Calculate this month's amounts
    const calculation = calculateMonthlyPension(grossSalary, config);

    // Calculate cumulative totals from previous contributions
    const lastContribution = previousContributions.length > 0
        ? previousContributions[previousContributions.length - 1]
        : null;

    const cumulativeEmployee = (lastContribution?.cumulative_employee || 0) + calculation.employeeContribution;
    const cumulativeEmployer = (lastContribution?.cumulative_employer || 0) + calculation.employerContribution;
    const cumulativeVoluntary = (lastContribution?.cumulative_voluntary || 0) + calculation.voluntaryContribution;
    const cumulativeTotal = cumulativeEmployee + cumulativeEmployer + cumulativeVoluntary;

    // Month tracking
    const monthNumber = previousContributions.length + 1;
    const totalServiceMonths = monthNumber + (config.preexisting_pension_months || 0);

    // Format period label (e.g., "December 2025")
    const periodLabel = month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

    // Set contribution month to first day of month
    const contributionMonth = new Date(month.getFullYear(), month.getMonth(), 1);

    return {
        staff_pension_id: config.id,
        payroll_run_id: payrollRunId,
        user_id: config.user_id,
        school_id: config.school_id,
        contribution_month: contributionMonth.toISOString().split('T')[0],
        period_label: periodLabel,
        gross_salary: grossSalary,

        // Config snapshot at time of calculation
        employee_type: config.employee_contribution_type,
        employee_value: config.employee_contribution_value,
        employer_enabled: config.employer_contribution_enabled,
        employer_type: config.employer_contribution_type,
        employer_value: config.employer_contribution_value,
        voluntary_enabled: config.voluntary_contribution_enabled,
        voluntary_type: config.voluntary_contribution_type,
        voluntary_value: config.voluntary_contribution_value,

        // This month's amounts
        employee_contribution: calculation.employeeContribution,
        employer_contribution: calculation.employerContribution,
        voluntary_contribution: calculation.voluntaryContribution,
        total_contribution: calculation.totalContribution,
        deduction_from_salary: calculation.deductionFromSalary,

        // Cumulative totals
        cumulative_employee: cumulativeEmployee,
        cumulative_employer: cumulativeEmployer,
        cumulative_voluntary: cumulativeVoluntary,
        cumulative_total: cumulativeTotal,

        // Month tracking
        month_number: monthNumber,
        total_service_months: totalServiceMonths,

        status: 'recorded',
    };
}

/**
 * Calculate comprehensive pension summary
 * @param config - Staff pension configuration
 * @param contributions - All contribution records for the staff member
 * @param userName - Staff member's name
 * @returns Complete pension summary
 */
export function calculatePensionSummary(
    config: StaffPension,
    contributions: PensionContribution[],
    userName: string
): PensionSummary {
    // Get latest contribution for cumulative totals
    const latestContribution = contributions.length > 0
        ? contributions[contributions.length - 1]
        : null;

    const cumulativeEmployee = latestContribution?.cumulative_employee || 0;
    const cumulativeEmployer = latestContribution?.cumulative_employer || 0;
    const cumulativeVoluntary = latestContribution?.cumulative_voluntary || 0;
    const cumulativeTotal = cumulativeEmployee + cumulativeEmployer + cumulativeVoluntary;
    const grandTotal = cumulativeTotal + (config.preexisting_pension_amount || 0);

    // Get recent contributions (last 12 months)
    const recentContributions = contributions.slice(-12);

    return {
        staffName: userName,
        pensionProvider: config.pension_provider,
        pensionPin: config.pension_pin,
        isEnrolled: config.is_enrolled,
        enrollmentDate: config.enrollment_date,

        // Preexisting pension
        hasPreexisting: config.has_preexisting_pension,
        preexistingAmount: config.preexisting_pension_amount || 0,
        preexistingMonths: config.preexisting_pension_months || 0,

        // Current configuration
        employeeContributionType: config.employee_contribution_type,
        employeeContributionValue: config.employee_contribution_value,
        employerEnabled: config.employer_contribution_enabled,
        employerContributionType: config.employer_contribution_type,
        employerContributionValue: config.employer_contribution_value,
        voluntaryEnabled: config.voluntary_contribution_enabled,
        voluntaryContributionType: config.voluntary_contribution_type,
        voluntaryContributionValue: config.voluntary_contribution_value,

        // Totals
        totalMonthsContributed: contributions.length,
        totalServiceMonths: (latestContribution?.total_service_months || 0) || config.preexisting_pension_months || 0,
        cumulativeEmployee,
        cumulativeEmployer,
        cumulativeVoluntary,
        cumulativeTotal,
        grandTotal,

        // Recent contributions
        recentContributions,
    };
}

/**
 * Format amount in Nigerian Naira
 * @param amount - Amount to format
 * @returns Formatted currency string
 */
export function formatNaira(amount: number): string {
    return new Intl.NumberFormat('en-NG', {
        style: 'currency',
        currency: 'NGN',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    }).format(amount);
}

/**
 * Format contribution type for display
 */
export function formatContributionType(type: ContributionInputType, value: number): string {
    if (type === 'percentage') {
        return `${value}%`;
    } else {
        return formatNaira(value);
    }
}
